name: CI/CD - Credit Default API

on:
  push:
    branches: [master, develop]
    tags:
      - "v*.*"
  pull_request:
    branches: [master, develop]

jobs:
  # ==========================
  # TEST JOB
  # ==========================
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Install joblib (for local model in tests)
        run: pip install joblib

      - name: Copy trained model for tests
        # Suppose que final_model.pkl et best_threshold.json sont commit√©s dans le repo
        run: |
          echo "Using pre-trained model for CI tests"
          ls -l outputs/final_model.pkl
          ls -l outputs/best_threshold.json

      
      # -----------------------------
      # FAST TESTS (PR + develop)
      # -----------------------------
      - name: Run fast tests (no long)
        if: github.ref_name != 'master'
        env:
          ENV: test
          PYTHONPATH: ${{ github.workspace }}
        run: pytest -m "not long" --maxfail=1 --disable-warnings -v -o log_cli_level=INFO

      # -----------------------------
      # FULL TEST SUITE (master)
      # -----------------------------
      - name: Run full test suite (including long)
        if: github.ref_name == 'master'
        env:
          ENV: test
          PYTHONPATH: ${{ github.workspace }}
        run: pytest --maxfail=1 --disable-warnings -v -o log_cli_level=INFO

  # ==========================
  # BUILD DOCKER IMAGE
  # ==========================
  build:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t credit-default-api .

  # ==========================
  # PUSH TO DOCKER HUB
  # ==========================
  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/credit-default-api:latest .

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/credit-default-api:latest

        